#Used DIG method/ Changed form_tag to form_with. Form used nested params, therefore in controller I use nested params[:post][:status]. But if getting data from nested parameters in a controller action I get NoMethodError: undefined method '[]' for nil:NilClass. As a result, I use dig method with help article#2 on the  site : https://rollbar.com/blog/top-10-ruby-on-rails-errors/